9 cicd pipeline
atlas-aero/rt-mcp2517 pull request #10
Opened 2024-04-29 13:24 UTC by HusseinAbdelhamid

2024-05-10 08:56 UTC, marius-meissner requested changes
The CI/CD pipeline seems to contain everything important (unit tests, build checks, code style, Clippy). Just one question regarding Atomics.

2024-05-10 08:56 UTC, marius-meissner commented on .github/workflows/qa.yaml
> +  no_std_no_atomics_builds:
Maybe I'm missing something, but isn't this block identical to `no_std_atomics_builds`?

2024-05-17 09:20 UTC, marius-meissner commented on .github/workflows/qa.yaml
> +  no_std_no_atomics_builds:
It might be a good approach to test here for thumbv6 instead. However, this does not work with the --target parameter, as for `bytes` crate, we currently need a patch on "end-user" crate level.
I just added an example folder, maybe you could try building it in the CI/CD pipeline.

As soon #2 is merged, you most probably need to include the following patch then:
https://github.com/atlas-aero/rt-bytes

2024-06-02 14:53 UTC, marius-meissner commented
What is the status here?
I may be missing something, but in the current state the example is not built in the QA pipeline, right?

2024-06-03 15:10 UTC, HusseinAbdelhamid commented
> What is the status here? I may be missing something, but in the current state the example is not built in the QA pipeline, right?

Yes not yet. Will probably have to include the rt-bytes patch locally instead because I get a git fetch error that requires

> What is the status here? I may be missing something, but in the current state the example is not built in the QA pipeline, right?

Correct, using the patch isn't quite straight forward in the QA pipeline, maybe include the bytes patch locally instead of using git fetch?

2024-06-07 10:53 UTC, marius-meissner commented
As you depend on bytes v1.6, you probably need to implement https://github.com/atlas-aero/rt-bytes/issues/3 first.

You also need to adjust the dependency integration, that no_std is supported:
```toml
bytes = { version = "1.6.0" , default-features = false}
```

2024-06-20 15:26 UTC, marius-meissner approved these changes
LGTM

2024-06-20 15:26 UTC, merged