5 add docs for crate usage
atlas-aero/rt-mcp2517 pull request #14
Opened 2024-09-03 12:48 UTC by HusseinAbdelhamid

2024-09-04 10:33 UTC, HusseinAbdelhamid commented
Should wait till PR #16 and #18 are merged first. Then will adjust the doc examples accordingly

2024-09-05 09:39 UTC, marius-meissner requested changes
A good start and nice examples. But the docs should be reorganized a bit:
1. Move the docs of the `can` module to crate level, as these act as a nice starting point for the user
2. Add comment description to all the modules
3. Add shorter + deeper descriptions and examples to the corresponding modules. In detail:
a) `can` module: Explain how to configure the CAN controller (e.g. FIFO configuraiton)
b) `message` module: Explain the two CAN types (CAN FD and CAN 2.0) and add short examples (just how to construct them)

2024-09-05 09:39 UTC, marius-meissner commented on Cargo.toml
> +[patch.crates-io]
Patches should not be used at library level. This only makes sense at the lowest level, i.e. the end user. Please remove again. In addition, this currently prevents the library from being built.

2024-09-05 09:39 UTC, marius-meissner commented on src/lib.rs
> +pub mod example;
Please add an example feature flag for. So the library user has the ability to remove the example code for prod. usage. 

See LTC681X crate as reference:
https://github.com/atlas-aero/rt-LTC681X/blob/6c4407091672e7dd2e91dda18d0a686246e4fbf2/Cargo.toml#L25

2024-09-05 10:14 UTC, HusseinAbdelhamid commented on Cargo.toml
> +[patch.crates-io]
Yes sorry, I was just testing something to use this branch with the BMS as currently importing the main branch of this library doesn't build.

2024-09-05 10:16 UTC, HusseinAbdelhamid commented
> 1. Move the docs of the `can` module to crate level, as these act as a nice starting point for the user

So the docs should be in a separate file?

2024-09-09 09:35 UTC, marius-meissner commented
> So the doc example should be in a separate file?

The intent was, to move the docs of `can.rs` to `lib.rs`. So that these docs are shown on the first page of the docs.

Furthermore, you might combine the RX and TX example into one. It is common practice that only one complete example is shown on the first documentation page. And then detailed examples are shown in the individual sub-pages or modules.

2024-09-10 12:21 UTC, HusseinAbdelhamid commented
Should be ready for another review now, I included the changes from #20 as well.

2024-09-12 09:47 UTC, marius-meissner requested changes
Really nicely elaborated documentation that will make it easier for both internal and external developers to get started.

2024-09-12 09:47 UTC, marius-meissner commented on src/lib.rs
> +//! Crate currently offer the following features:
```suggestion
//! Crate currently offers the following features:
```

2024-09-12 09:47 UTC, marius-meissner commented on src/lib.rs
> +//! * no_std support
```suggestion
//! * `no_std` support
```

2024-09-12 09:47 UTC, marius-meissner commented on src/example.rs
> +use alloc::vec;
Please add a short description, that the example code may be removed by disabling the example feature flag.

2024-09-12 09:47 UTC, marius-meissner commented on src/can.rs
> +//!
For keeping the specific examples shorter, it's common practice to hide some less important lines like the use statements.
```suggestion
//!# use mcp2517::can::Controller;
//!# use mcp2517::config::Configuration;
//!# use mcp2517::example::*;
//!#
```

2024-09-12 09:47 UTC, marius-meissner commented on src/config.rs
> +//! # CAN Module configuration
Really nice explanation of the configuration.

2024-09-12 09:47 UTC, marius-meissner commented on src/config.rs
> +//! to 8 bytes. The number of message the Rx Fifo buffer can hold is 10 while it is 32 for the Tx Fifo.
```suggestion
//! to 8 bytes. The number of message the RX Fifo buffer can hold is 10 while it is 32 for the Tx Fifo.
```

2024-09-12 09:47 UTC, marius-meissner commented on src/config.rs
> +//!
```suggestion
//!# use mcp2517::config::{FifoConfiguration,PayloadSize,RetransmissionAttempts};
//!#
```

2024-09-12 09:47 UTC, marius-meissner commented on src/config.rs
> +//!
```suggestion
//!# use mcp2517::config::{ClockConfiguration, ClockOutputDivisor, PLLSetting, SystemClockDivisor};
//!#
```

2024-09-12 09:47 UTC, marius-meissner commented on src/config.rs
> +//!
```suggestion
//!# use mcp2517::config::{BitRateConfig,CanBaudRate,SysClk};
//!#
```

2024-09-12 09:47 UTC, marius-meissner commented on src/lib.rs
> +//!let payload = [1, 2, 3, 4, 5, 6, 7, 8];
As we are transmitting binary data, hex representation is a bit more common to use and demonstrates that no kind of transformation is applied.
```suggestion
//!let payload = [0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8];
```

2024-09-12 09:47 UTC, marius-meissner commented on src/lib.rs
> +//!assert_eq!(buff,[1,2,3,4,5,6,7,8]);
```suggestion
//!assert_eq!(buff,[0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8]);
```

2024-09-12 09:47 UTC, marius-meissner commented on src/message.rs
> +//! let payload = [1,2,3,4,5,6,7,8];
```suggestion
//! let payload = [0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8];
```

2024-09-24 07:57 UTC, marius-meissner commented
Any updates on this?
As soon this PR is done, we could release the first version to crates.io. I assume this will help with development of our internal software.

2024-09-24 07:59 UTC, HusseinAbdelhamid commented
> Any updates on this? As soon this PR is done, we could release the first version to crates.io. I assume this will help with development of our internal software.

It's close to being finished, just need to update docs to match latest commits

2024-09-26 10:49 UTC, HusseinAbdelhamid commented
Should be updated with latest PRs, added a couple of comments and an example for constructing a CAN FD message as well

2024-10-01 08:19 UTC, HusseinAbdelhamid commented
Comments address now, should be ready for review

2024-10-01 10:42 UTC, marius-meissner requested changes
99% done, the only previous open comment:
https://github.com/atlas-aero/rt-mcp2517/pull/14#discussion_r1756508553

2024-10-01 10:42 UTC, marius-meissner commented on src/lib.rs
> +//!
Now you've done more than necessary :). 
In the very first main example, it is then usual to show the use statements again, so that you can see at first glance what other dependencies there are.
In addition, the user can at least copy this example with one click and try it out.

```suggestion
//! use mcp2517::example::{ExampleClock,ExampleCSPin,ExampleSPIBus};
//! use mcp2517::can::{MCP2517,CanController};
//! use mcp2517::message::{Can20,TxMessage};
//! use mcp2517::filter::Filter;
//! use mcp2517::config::*;
//! use bytes::Bytes;
//! use embedded_can::{Id,StandardId};
//!
```

2024-10-01 10:42 UTC, marius-meissner commented on src/message.rs
> +//!
```suggestion
```

2024-10-01 10:54 UTC, HusseinAbdelhamid commented on src/lib.rs
> +//!
Got it :+1:

2024-10-15 10:55 UTC, marius-meissner approved these changes
LGTM

2024-10-15 10:55 UTC, merged