#27 make TxMessage data members public
atlas-aero/rt-mcp2517 pull request #28
Opened 2024-09-24 12:52 UTC by HusseinAbdelhamid

see #27

2024-09-24 14:24 UTC, marius-meissner requested changes
I don't think it's worth giving up OOP or stability and security principles just because of tests.
What about just adding getter methods, which return immutable borrows?
This would also have the advantage that these methods may also be helpful outside of tests.

2024-09-24 14:31 UTC, HusseinAbdelhamid commented
> I don't think it's worth giving up OOP or stability and security principles just because of tests. What about just adding getter methods, which return immutable borrows? This would also have the advantage that these methods may also be helpful outside of tests.

Yes probably a better idea, so as an example to get the buff member we could implement a fn like this: 
```rust
  pub fn get_payload(&self) -> &Bytes {
        &self.buff
    }
```

2024-09-26 09:51 UTC, marius-meissner commented on src/tests/message.rs
> +#[test]
Even with unit test, nice :) :+1:

2024-09-26 09:51 UTC, marius-meissner approved these changes
LGTM

2024-09-26 09:51 UTC, merged