32 migrate to hal 10
atlas-aero/rt-mcp2517 pull request #33
Opened 2024-12-05 10:50 UTC by HusseinAbdelhamid

2024-12-09 11:04 UTC, marius-meissner requested changes
Looks good :+1: 
Just one tiny suggestions (s. inline comment). 

Maybe you can in addition the following targets to QA pipeline:
* thumbv7m-none-eabi (Raspberry Pi)
* thumbv8m.main-none-eabihf (RP2350)
* riscv32imac-unknown-none-elf (RP2350 alternative)

2024-12-09 11:04 UTC, marius-meissner commented on src/example.rs
> +    }
That's quite a deep if nesting. It's example code, so it's already whining on a high level :)
Maybe you can make the statement a bit flatter with “ealry returns”.

2024-12-09 11:59 UTC, HusseinAbdelhamid commented
Changes addressed now :+1:

2024-12-10 08:31 UTC, marius-meissner approved these changes
LGTM

2024-12-10 08:31 UTC, merged