2 implement message transmission
atlas-aero/rt-mcp2517 pull request #4
Opened 2024-04-16 12:29 UTC by HusseinAbdelhamid

2024-04-18 21:50 UTC, marius-meissner requested changes
Generally nice API structure, relatively good test coverage and good idea with the use of Bitfield. :+1: 

A few general suggestions upfront:

**1. Rust docs**
Rust has a really impressive documentation system for generating docs out of source code comments. This even includes code segments, which will be executed during unit tests and can act as some kind of integration tests.

Since this is or will be a public open source project and also independent of it, it makes sense to have some documentation. This concerns the general use of the library, but also the description of individual structures.
We should implement the documentation for general use in a separate PR for not blowing up this PR, see the following issue for more details:
https://github.com/atlas-aero/rt-mcp2517/issues/5

**2. Building for embedded targets**
Building for embedded targets like `thumbv6m` fails. But seems this is also the case for main branch. So this can be fixed then in a different PR then.
https://github.com/atlas-aero/rt-mcp2517/issues/7

**3. Unused code warnings**
The compiler complains about a few unused functions. All of them refer to generated code by bitfield. Unfortunately, adding `#[allow(dead_code)]` to the corresponding structs does not work. So I assume you need to disable these inspections on module level `#![allow(dead_code)]`

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
> +pub enum TestError<B, CS> {
Is this enum used anywhere?

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
> +#[derive(Debug)]
Please add a blank line between code blocks for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
> +    ConfigErr(ConfigError<B, CS>),
Please add a short comment on each variant, explaining the error source. These comments are then also automatically included by `cargo doc`

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
> +    pub fn reset(&mut self) -> Result<(), BusError<B::Error, CS::Error>> {
1. Please add a doc comment for this function.
2. Seems this function is currently not covered by any unit tests. Please try to implement at least one test.

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
> +    pub fn transmit(&mut self, message: TxMessage) -> Result<(), Error<B::Error, CS::Error>> {
1. Please add a doc comment for this function.
2. Seems this function is currently not covered by any unit tests. Please try to implement at least one test.

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
> +        while !txfifo_status_reg0.tfnrfnif() {}
Isn't this blocking forever, as the data is not refreshed?
If this is fixed/check, please add a unit tests for full FIFO case.

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
> +        while txfifo_control_reg.txreq() {}
Another infinity loop here?
As stated before, please cover waiting for confirmation in unit tests as well.

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
>      /// Reads a single register byte
Please add blank lines between function blocks for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
> +    /// Returns the address of fifo user address register for the given index
Please add blank lines between function blocks for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/can.rs
> +            return Err(Error::InvalidRamAddress(addr));
Is this just an internal assertion, or is it possible for a crate user triggering this kind of error?
If the second case is true, please add a unit test for that.

2024-04-18 21:50 UTC, marius-meissner commented on src/message.rs
> +#[derive(Debug, Eq, PartialEq, Ord, PartialOrd)]
Please add a blank line above.

2024-04-18 21:50 UTC, marius-meissner commented on src/message.rs
> +    InvalidLength(usize),
Please add a doc comment.

2024-04-18 21:50 UTC, marius-meissner commented on src/message.rs
> +pub struct TxHeader {
Please also add doc comment on the struct members.
These register values can of course also be looked up in the datasheet, but it is sometimes easier if these are briefly described directly in the code.

2024-04-18 21:50 UTC, marius-meissner commented on src/message.rs
> +pub struct TxMessage {
Same here, please add a doc comments to the struct members.

2024-04-18 21:50 UTC, marius-meissner commented on src/message.rs
> +        // make sure length divisible by four (word size)
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/message.rs
> +        Ok(TxMessage {
Please add a blank line between line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/message.rs
> +        while let Err(DLCError::InvalidLength(_)) = DLC::from_length(payload_length) {
In general, a cool idea for finding the next bigger size, but not sure whether it is the most efficient way to solve this.
Please check if maybe using `binary_search` makes sense here:
https://doc.rust-lang.org/std/primitive.slice.html#method.binary_search

2024-04-18 21:50 UTC, marius-meissner commented on src/message.rs
> +impl DLC {
Clippy has a false-positive warning here:
```rust
warning: name `DLC` contains a capitalized acronym
  --> src/message.rs:13:10
   |
13 | pub enum DLC {
   |          ^^^ help: consider making the acronym lowercase, except the initial letter: `Dlc`
```

Can be suppressed using `#[allow(clippy::upper_case_acronyms)]`.

2024-04-18 21:50 UTC, marius-meissner commented on src/registers.rs
> +impl FifoControlReg3 {
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/registers.rs
> +pub struct FifoControlReg2 {
Same here, please add doc comments for the struct members.

2024-04-18 21:50 UTC, marius-meissner commented on src/registers.rs
> +pub struct FifoControlReg1 {
Same here, please add doc comments for the struct members.

2024-04-18 21:50 UTC, marius-meissner commented on src/registers.rs
> +pub struct FifoControlReg0 {
Same here, please add doc comments for the struct members.

2024-04-18 21:50 UTC, marius-meissner commented on src/registers.rs
> +/// First byte of FIFO Status register
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/registers.rs
> +pub struct FifoStatusReg0 {
Same here, please add doc comments for the struct members.

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/message.rs
> +    assert!(message.header.identifier_extension_flag());
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/message.rs
> +#[test]
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/message.rs
> +    assert!(!message.header.identifier_extension_flag());
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/message.rs
> +#[test]
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/message.rs
> +    assert_eq!(message.header.data_length_code(), DLC::Sixteen);
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/message.rs
> +    let header_bytes = message.header.into_bytes();
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/message.rs
> +    assert_eq!(message_2_0.unwrap_err(), DLCError::InvalidLength(10));
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/registers.rs
> +#[test]
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/registers.rs
> +    assert_eq!([0b1000_0000], FifoControlReg0::new().with_txen(true).into_bytes());
Well done, using the binary representation for easier readability :+1:

2024-04-18 21:50 UTC, marius-meissner commented on src/tests/registers.rs
> +#[test]
Please add a blank line above for easier readability.

2024-04-18 21:50 UTC, marius-meissner commented on src/message.rs
> +    pub fn new(identifier: Id, data: &[u8], can_fd: bool, bitrate_switch: bool) -> Result<Self, DLCError> {
In general, copying from a slice to a buffer is a common practice.
However, there are also zero-copy options for Rust. Have a look at whether the use of [bytes](https://crates.io/crates/bytes) might be an option, which is often used in network programming in particular.

2024-04-25 10:32 UTC, marius-meissner requested changes
Thanks, PR is getting close for being merged.
Please also check unresolved comments from the previous review.

2024-04-25 10:32 UTC, marius-meissner commented on src/can.rs
> +        let mut txfifo_status_byte0 = self.read_register(Self::fifo_status_register(FIFO_TX_INDEX))?;
What about saving the result of `Self::fifo_status_register(FIFO_TX_INDEX)` in a local variable, as the address is used at least twice?
Might save some CPU time.

2024-04-25 10:32 UTC, marius-meissner commented on src/tests/can.rs
> +fn test_transmit() {
Test looks quite good! Good structure (including comments), which makes it easy to understand.
Two small suggestions:
1. Please try to use here `Sequence` as well. I assume its enough to ensure that CS and transfer operations are in correct order.
2. Is this behaviour covered by the test? https://github.com/atlas-aero/rt-mcp2517/blob/666dff369c6f6283cf3d826a211d49ea0ec965ca/src/can.rs#L187
If not, please try to adjust the test, that at least one wait loop is executed.

2024-04-25 10:32 UTC, marius-meissner commented on src/tests/can.rs
> +    mocks.bus.expect_transfer().times(1).returning(move |data| {
Same here, please try to adjust the test, that atleast one iteration of the following loop is covered:
https://github.com/atlas-aero/rt-mcp2517/blob/666dff369c6f6283cf3d826a211d49ea0ec965ca/src/can.rs#L212

2024-04-25 10:32 UTC, marius-meissner commented on src/registers.rs
> +/// Fourth byte of FIFO Control register
Please add a blank line above for easier readability.

2024-04-25 10:32 UTC, marius-meissner commented on src/can.rs
> +    /// Verify address within RAM bounds
Please add a blank line above for easier readability.

2024-04-25 10:32 UTC, marius-meissner commented on src/config.rs
> +#[derive(Copy, Clone, Debug, PartialEq)]
Please add a blank line above + short comment that explains that this enums ensures that just defined payload sizes are possible.

2024-04-25 10:32 UTC, marius-meissner commented on src/lib.rs
> +pub mod registers;
Seems none of the structs in `registers` are exposed in the public API. So please check if this really needs to be public.

2024-04-25 10:32 UTC, marius-meissner commented on src/message.rs
> +    pub fn new(identifier: Id, data: &[u8], can_fd: bool, bitrate_switch: bool) -> Result<Self, DLCError> {
Ok, maybe that was a bit misleading. The idea would be that the caller passes a bytes object. The advantage is that bytes objects can be cloned without the data being copied.
Bytes also allows to just have a slice of data, without copying:
https://docs.rs/bytes/1.6.0/bytes/struct.Bytes.html#method.slice

2024-04-25 10:32 UTC, marius-meissner commented on src/tests/can.rs
> +    pub fn mock_read32<const REG: u32>(&mut self, expected_command: [u8; 2]) {
Please add a blank line above.

2024-04-25 10:32 UTC, marius-meissner commented on src/tests/message.rs
> +fn test_extended_id() {
The idea was to structure the code into blocks in a more readable way. In the case of the tests, to separate the test structure from the checks. Something like this:
```rust
#[test]
fn test_extended_id() {
    let data = [0u8; 8];
    let extended_id = ExtendedId::new(EXTENDED_ID).unwrap();
    let message = TxMessage::new(Id::Extended(extended_id), &data, false, false).unwrap();

    assert!(message.header.identifier_extension_flag());
    assert_eq!(message.header.extended_identifier(), 0b01_0010_1010_0010_1011);
    assert_eq!(message.header.standard_identifier(), 0b101_0011_0010);
}
```

2024-04-25 10:32 UTC, marius-meissner commented on src/tests/message.rs
> +#[test]
Same here, general rule is to have a blank line between each test or in general between each function implementation.

2024-04-25 10:34 UTC, marius-meissner commented
In addition, please try to resolve all Clippy warnings:

> warning: this operation has no effect
>  --> src/registers.rs:2:1
>   |
> 2 | / /// Fourth byte of FIFO Control register
> 3 | | #[bitfield]
> 4 | | #[derive(Default)]
> 5 | | #[repr(u8)]
> ... |
> 8 | |     fsize: B5,
> 9 | | }
>   | |_^ help: consider reducing it to: `pub plsize: B3`
>   |
>   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_op
>   = note: `#[warn(clippy::identity_op)]` on by default
> 
> warning: this operation has no effect
>  --> src/registers.rs:2:1
>   |
> 2 | / /// Fourth byte of FIFO Control register
> 3 | | #[bitfield]
> 4 | | #[derive(Default)]
> 5 | | #[repr(u8)]
> ... |
> 8 | |     fsize: B5,
> 9 | | }
>   | |_^ help: consider reducing it to: `pub plsize: B3`
>   |
>   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_op
> 
> warning: this operation has no effect
>   --> src/registers.rs:23:1
>    |
> 23 | / /// Third byte of FIFO Control register
> 24 | | #[bitfield]
> 25 | | #[derive(Default)]
> 26 | | #[repr(u8)]
> ...  |
> 31 | |     pub txpri: B5,
> 32 | | }
>    | |_^
>    |
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_op
> help: consider reducing it to
>    |
> 23 + #[skip]
> 24 +     __: B1
>    |
> 
> warning: this operation has no effect
>   --> src/registers.rs:34:1
>    |
> 34 | / /// Second byte of FIFO Control register
> 35 | | #[bitfield]
> 36 | | #[derive(Default)]
> 37 | | #[repr(u8)]
> ...  |
> 43 | |     pub uinc: bool,
> 44 | | }
>    | |_^
>    |
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_op
> help: consider reducing it to
>    |
> 34 + #[skip]
> 35 +     __: B5
>    |
> 
> warning: this operation has no effect
>   --> src/registers.rs:46:1
>    |
> 46 | / /// First byte of FIFO Control register
> 47 | | #[bitfield]
> 48 | | #[derive(Default)]
> 49 | | #[repr(u8)]
> ...  |
> 58 | |     pub tfnrfnie: bool,
> 59 | | }
>    | |_^ help: consider reducing it to: `pub txen: bool`
>    |
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_op
> 
> warning: this operation has no effect
>   --> src/registers.rs:61:1
>    |
> 61 | / /// Second byte of FIFO Status register
> 62 | | #[bitfield]
> 63 | | #[derive(Default)]
> 64 | | #[repr(u8)]
> ...  |
> 68 | |     pub fifoci: B5,
> 69 | | }
>    | |_^
>    |
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_op
> help: consider reducing it to
>    |
> 61 + #[skip]
> 62 +     __: B3
>    |
> 
> warning: this operation has no effect
>   --> src/registers.rs:70:1
>    |
> 70 | / /// First byte of FIFO Status register
> 71 | |
> 72 | | #[bitfield]
> 73 | | #[derive(Default)]
> ...  |
> 83 | |     pub tfnrfnif: bool,
> 84 | | }
>    | |_^ help: consider reducing it to: `pub txabt: bool`
>    |
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_op
> 
> warning: `mcp2517` (lib) generated 12 warnings (5 duplicates) (run `cargo clippy --fix --lib -p mcp2517` to apply 7 suggestions)
>     Finished dev [unoptimized + debuginfo] target(s) in 0.30s

2024-04-25 14:59 UTC, marius-meissner commented
Please ping me or add a comment, as soon PR is ready for another review.

2024-04-25 20:56 UTC, marius-meissner commented
> > Please ping me or add a comment, as soon PR is ready for another review.
> 
> Got it, should be ready now

Please check all open review comments to ensure they have been addressed. At least the following five comments are still unprocessed or unanswered:
- https://github.com/atlas-aero/rt-mcp2517/pull/4/files#r1579228237
- https://github.com/atlas-aero/rt-mcp2517/pull/4/files#r1571399932
- https://github.com/atlas-aero/rt-mcp2517/pull/4/files#r1579229850
- https://github.com/atlas-aero/rt-mcp2517/pull/4/files#r1571401182
- https://github.com/atlas-aero/rt-mcp2517/pull/4/files#r1571401815

2024-04-26 07:16 UTC, HusseinAbdelhamid commented on src/can.rs
> +            return Err(Error::InvalidRamAddress(addr));
Its only internal assertion that i use in `transmit` when loading the message in the FIFO

2024-04-26 07:42 UTC, HusseinAbdelhamid commented on src/message.rs
> +        while let Err(DLCError::InvalidLength(_)) = DLC::from_length(payload_length) {
I don't think it can be used as it's part of the std library

2024-04-26 09:47 UTC, HusseinAbdelhamid commented
Would it be a good idea to add this [rustfmt config](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#blank_lines_lower_bound) set to 1 in rustfmt.toml? it does however leave spaces between all lines of code within function bodies as well which may not be desirable

2024-05-06 18:50 UTC, marius-meissner requested changes
Very nice! It already looks very good.
Just another new comment regarding `BytesMut`.

Please keep an eye on the three old unresolved minor comments:
- https://github.com/atlas-aero/rt-mcp2517/pull/4/files#r1571426267
- https://github.com/atlas-aero/rt-mcp2517/pull/4/files#r1571426573
- https://github.com/atlas-aero/rt-mcp2517/pull/4/files#r1571426667

2024-05-06 18:50 UTC, marius-meissner commented on src/can.rs
> +            return Err(Error::InvalidRamAddress(addr));
Alright, thanks!

2024-05-06 18:50 UTC, marius-meissner commented on src/message.rs
> +    pub fn new(identifier: Id, mut data: BytesMut, can_fd: bool, bitrate_switch: bool) -> Result<Self, DLCError> {
Do you think it's possible to use `Bytes` instead of `BytesMut.`
The only mutable operation is currently `data.resize(length, 0)`. Maybe an alternative is using `slice`?:
https://docs.rs/bytes/1.6.0/bytes/struct.Bytes.html#method.slice

In practice, simple `Byte` objects are much more common because they are much easier to handle without mutability. That's the beauty of Bytes, that you can get and keep individual slices without mutability.

2024-05-06 18:50 UTC, marius-meissner commented on src/tests/can.rs
> +fn test_transmit() {
Nice. Well done!

2024-05-06 18:50 UTC, marius-meissner commented on src/message.rs
> +        while let Err(DLCError::InvalidLength(_)) = DLC::from_length(payload_length) {
Ahh, you are right!

2024-05-07 07:51 UTC, HusseinAbdelhamid commented on src/message.rs
> +    pub fn new(identifier: Id, mut data: BytesMut, can_fd: bool, bitrate_switch: bool) -> Result<Self, DLCError> {
I did try using `Bytes` in the previous PR review but the SPI bus `transfer` function requires a mutable I think so that data is written back into it the `BytesMut` object `message.buff`. Otherwise I get this error 

<pre><font color="#F66151"><b>error[E0596]</b></font><b>: cannot borrow data in dereference of `bytes::Bytes` as mutable</b>
   <font color="#2A7BDE"><b>--&gt; </b></font>src/can.rs:237:27
    <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>237</b></font> <font color="#2A7BDE"><b>|</b></font>         self.bus.transfer(&amp;mut message.buff).map_err(TransferError)?;
    <font color="#2A7BDE"><b>|</b></font>                           <font color="#F66151"><b>^^^^^^^^^^^^^^^^^</b></font> <font color="#F66151"><b>cannot borrow as mutable</b></font>
    <font color="#2A7BDE"><b>|</b></font>
    <font color="#2A7BDE"><b>= </b></font><b>help</b>: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `bytes::Bytes`
</pre>

2024-05-10 08:50 UTC, marius-meissner requested changes
Ok, one more minor change suggestion. This discussion probably seems too long, but since this is a network library, performance and memory management is very important and usually worth the effort. But now we're almost there.

2024-05-10 08:50 UTC, marius-meissner commented on src/message.rs
> +    pub fn new(identifier: Id, mut data: BytesMut, can_fd: bool, bitrate_switch: bool) -> Result<Self, DLCError> {
Ok, I think `BytesMut` gives to less advantage for keeping the current implementation. So I would suggest the following two changes:
1. Change BytesMut to Bytes in Message (this avoids copying the data, when the caller creates the Message object)
2. Change `mut message: TxMessage` to `message: &TxMessage` of `write_fifo()` method. This allows the caller to reuse the message object, when sending the same data or request over and over again
3. Copy data of Message object to a mutable buffer for calling self.bus.transfer. This keeps the original data clean.

2024-05-15 21:28 UTC, marius-meissner requested changes
Your approach of using BytesMut seems to be a good idea, but has the disadvantage that its using Heap. For a maximum size of 64 bytes, however, this is not worthwhile, as on the one hand this tends to be very slow and in the embedded area, if possible, heap allocation should be used as little as possible for stability reasons.

In general, 64 bytes or 8 bytes for CAN 2.0 is a typical size that can be stored on the stack without any problems.

Suggestion: Always allocate the maximum possible size as an array.
For optimization purposes, the maximum size (64 bytes for CAN FD and 8 bytes for CAN 2.0) could be stored as a generic const in the message object.

Perhaps something like this:
```rust
/// Transmit Message Object
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub struct TxMessage<T> {
    /// [...]
    /// CAN message type
    pub(crate) msg_type: T
}

impl<T: MessageType<MAX_LENGTH>, const MAX_LENGTH: usize> TxMessage<T> {
    pub fn new(identifier: Id, data: Bytes, msg_type: T) -> Result<Self, DLCError> {
        let mut header = TxHeader::new();
        let mut payload_length = data.len();

        if payload_length > MAX_LENGTH {
            debug!("Maximum of {MAX_LENGTH} data bytes allowed for message type. Current size: {payload_length}");
            return Err(DLCError::InvalidLength(data.len()));
        }
        
        msg_type.prepare(&mut header)?;
        
        // [...]

        Ok(TxMessage {
            header,
            buff: data,
            length,
            msg_type,
        })
    }
}

/// Trait, which is intended to represent the topology for different CAN message types.
pub trait MessageType<const MAX_LENGTH: usize> {
    /// Prepares the header and does assertions based on message type restrictions
    fn prepare(&self, _header: &mut TxHeader) -> Result<(), DLCError> {
        Ok(())
    }
}

/// CAN message type with flexible data rate
pub struct CanFD {
    /// True if bitrate needs to be switched
    bitrate_switch: bool
}

impl MessageType<64> for CanFD {
    fn prepare(&self, header: &mut TxHeader) -> Result<(), DLCError> {
        header.set_fd_frame(true);

        if self.bitrate_switch {
            header.set_bit_rate_switch(true);
        }

        Ok(())
    }
}

/// CAN 2.0 message type
pub struct Can20 {}

impl MessageType<8> for Can20 {}
```

But feel free to tell me if you have a different opinion.

2024-05-15 21:28 UTC, marius-meissner commented on src/message.rs
> +    pub(crate) length: usize,
What about using the `slice()` method of Bytes?:
https://docs.rs/bytes/1.6.0/bytes/struct.Bytes.html#method.slice

This would save the need to save the length. At least I don't currently see any place that accesses the buffer across the length.

2024-05-16 08:05 UTC, HusseinAbdelhamid commented on src/message.rs
> +    pub(crate) length: usize,
> What about using the `slice()` method of Bytes?: https://docs.rs/bytes/1.6.0/bytes/struct.Bytes.html#method.slice
> 
> This would save the need to save the length. At least I don't currently see any place that accesses the buffer across the length.

Can you explain more on that? the main purpose for length here was to identify the closest length divisible by four (i.e word size), so that no bytes are ignored during SPI transfer.

2024-05-17 08:34 UTC, marius-meissner commented on src/can.rs
> +    fn write_fifo<T, const L: usize>(
Very nice solution. Well done!

2024-05-17 08:40 UTC, marius-meissner requested changes
I think the PR is really almost perfect now. Just two more tiny suggestions and then we'll be good to go.

2024-05-17 08:40 UTC, marius-meissner commented on src/can.rs
> +use bytes::BytesMut;
Seems this import is unused now:

> warning: unused import: `bytes::BytesMut`
>  --> src/can.rs:7:5
>   |
> 7 | use bytes::BytesMut;
>   |     ^^^^^^^^^^^^^^^
>   |
>   = note: `#[warn(unused_imports)]` on by default

2024-05-17 08:40 UTC, marius-meissner commented on src/message.rs
> +    pub fn new(identifier: Id, data: Bytes, message_type: T) -> Result<Self, DLCError> {
Somehow it would feel better to me if the message type was the first parameter. Then we would have kept the order from general to specific.
What do you think?

2024-05-17 08:50 UTC, HusseinAbdelhamid commented on src/message.rs
> +    pub fn new(identifier: Id, data: Bytes, message_type: T) -> Result<Self, DLCError> {
> What do you think?

Yes I think it makes sense more if it's in that order

2024-05-24 14:41 UTC, merged